apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfwg-metrics
labels:
  - pairs:
      app.kubernetes.io/name: bfwg-metrics
    includeSelectors: false
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
